name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

<<<<<<< HEAD
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jayalakshmi143/docker-ci:latest

=======
      - name: Build Docker image
        run: docker build -t jayalakshmi143/docker-ci:latest .

      - name: Push Docker image to Docker Hub
        run: docker push jayalakshmi143/docker-ci:latest
>>>>>>> 63a0903 (Initial commit with CI/CD setup)
