name: Build and Push (Ubuntuvmware Runner)

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: [self-hosted, ubuntuvmware]  # Runs only on ubuntuvmware runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t my-docker-image-ubuntuvmware:latest .

      - name: Push Docker image
        run: docker push my-docker-image-ubuntuvmware:latest
