name: Develop Branch CI/CD (Runner 1)

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: [self-hosted, runner-1]  # Runs on runner-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t mydockerhub/my-docker-image-runner1:latest .

      - name: Push Docker image
        run: docker push mydockerhub/my-docker-image-runner1:latest
